	.set noreorder

#include "pspimport.s"

IMPORT_START	"sceJpeg",0x00090000
IMPORT_FUNC	"sceJpeg",0x0425B986,sceJpeg_0425B986
IMPORT_FUNC	"sceJpeg",0x04B5AE02,sceJpegMJpegCsc
IMPORT_FUNC	"sceJpeg",0x04B93CEF,sceJpegDecodeMJpeg
IMPORT_FUNC	"sceJpeg",0x227662D7,sceJpeg_227662D7
IMPORT_FUNC	"sceJpeg",0x48B602B7,sceJpegDeleteMJpeg
IMPORT_FUNC	"sceJpeg",0x64B6F978,sceJpeg_64B6F978
IMPORT_FUNC	"sceJpeg",0x67F0ED84,sceJpeg_67F0ED84
IMPORT_FUNC	"sceJpeg",0x7D2F3D7F,sceJpegFinishMJpeg
IMPORT_FUNC	"sceJpeg",0x8F2BB012,sceJpegGetOutputInfo
IMPORT_FUNC	"sceJpeg",0x91EED83C,sceJpegDecodeMJpegYCbCr
IMPORT_FUNC	"sceJpeg",0x9B36444C,sceJpeg_9B36444C
IMPORT_FUNC	"sceJpeg",0x9D47469C,sceJpegCreateMJpeg
IMPORT_FUNC	"sceJpeg",0xAC9E70E6,sceJpegInitMJpeg
